hosts:

  thinkcentre:
    ip_address: 192.168.0.7
    host_name: hydra-1
    user: eyelady
    role: master

  ideapad:
    ip_address: 192.168.0.38 
    host_name: hydra-2
    user: eyelady
    role: worker

  raspberrypi_3b:
    ip_address: 192.168.0.78
    host_name: hydra-3
    user: eyelady
    role: worker

  raspberrypi_3bplus:
    ip_address: 192.168.0.168
    host_name: hydra-4
    user: eyelady
    role: worker

