hosts:

  thinkcentre:
    ip_address: 192.168.0.7
    host_name: hydra-1
    user: eyelady
    role: master
    resources:
      cpu: AMD Ryzen 5 Pro 2400GE 8c
      gpu: Radeon Vega Integrated
      memory: 15gb
      storage:
        sda: 225gb
        nvme0n1: 1tb


  ideapad:
    ip_address: 192.168.0.38 
    host_name: hydra-2
    user: eyelady
    role: worker
    resources:
      cpu: AMD A12-9720P Radeon R7 4c
      gpu: Radeon R7 Integrated
      memory: 11gb
      storage:
        sda: 1tb


  raspberrypi_3b:
    ip_address: 192.168.0.78
    host_name: hydra-3
    user: eyelady
    role: worker
    resources:
      cpu: ARM 4c 
      gpu: Integrated
      memory: 1gb
      storage:
        mmcblk0: 116gb


  raspberrypi_3bplus:
    ip_address: 192.168.0.168
    host_name: hydra-4
    user: eyelady
    role: worker
    resources:
      cpu: ARM 4c 
      gpu: Integrated
      memory: 1gb
      storage:
        mmcblk0: 16gb



  Ideapad:
    ip_address: 192.168.0.178 
    host_name: hydra-5
    user: keegan
    role: worker
    resources:
      cpu: AMD Ryzen 7 4700U 8c  
      gpu: AMD Vega Integrated
      memory: 18gb
      storage:
        nvme0n1: 476gb
